### ISSUE TITLE
Problems sending larger data junks - data splitted on receive

### ISSUE THREAD

**Issue by irieger** [IronsDu/brynet#70]
Hey, I stumbled past brynet a few times and thought that I should give it a try. I'm doing a small proof of concept simple binary data send/receive in the local network (image transfer for displaying on another machine). As I want to keep dependencies low and prefer not to depend on a big codebase as boost, brynet catched my eye. The base was easy to understand with the sample PingPongClient/Server and my adaptation looked good. However there is one showstopper for me:

### Data fragmentation

(Modified sample code used here: https://gist.github.com/irieger/74808b0db67c39e33d37641e210e26bc)

Without finding a documentation I expected the send/receive code to abstract the fragmentation and split/combine data into the fragments needed for network transfer. For example sending an image with 1920x1080 pixels with RGBA (4 channels) of float32 data the image has already 33177600 bytes. Or in the sample code 1920*1080 with 3 channels of uint16_t 74649600 bytes. Therefore I set WithMaxRecvBufferSize(1535 * 1024 * 1024); and just send the data in the client. The data consist of a simple header (format[int32_t], height[uint32_t], width[uint32_t]) + the image data, thus in my sample 33177612 bytes. (Sample code above adapted as the actual code is inside another project, but the sample code shows the effect)

This data is now received via three calls of my callback (set with setDataCallback). My test code (interpreting the first 12 bytes as the header so any data there is expected to represent my format, height and width) results in a correct expected size for the first junk and invalid expected sizes afterwards instead of one received package. Combined the size is correct:
```
Received image smaller than described by header
     Expected: 33177612, got: 65482
Received image smaller than described by header
     Expected: 3044704916, got: 65482
Received image smaller than described by header
     Expected: 4185915404, got: 33046648
```
Three calls to the callback seem to be reproducible when only one transfer happens. When sending two images in parallel the callback is executed a varying number of times, some samples are 387 or 403 times. However using a different buffer size like 512 MB the number of packets differs.

Is there an integrated way to send/receive larger binary junks reliable at once or would some boilerplate be needed to split and receive in junks below a certain limit? Where is the limit or how would one need to modify the examples for larger datasets?

**Comment by IronsDu** [comment]
Hi,  the first, I'm sorry not support englisth version document.

1. ` using DataCallback = std::function<size_t(const char* buffer, size_t len)>;`, it's return type is `size_t`,  it's value indicate how many data processed.  if return size less than the input len, the left buffer will remain in TcpConnection's internal buffer, the buffer will  pass by next DataCallback when TcpConnection's socket receive next packet.
2. In your example code, it's dataCallback implement  not correct. You can refer to  other example: https://github.com/IronsDu/brynet/blob/master/examples/BroadCastServer.cpp#L98。
3. So ,why splitted on receive？ Because TCP is a stream-oriented protocol， One send may be receive multi times。
4. Otherwise,  `WithMaxRecvBufferSize` only set the limit size of TcpConnection's internal receive buffer, but it's current size may be less than limit.

Thank you try brynet.

**Comment by IronsDu** [comment]
You can see here. https://github.com/IronsDu/brynet/blob/b0d13e7419628d0f7051a2bb310daaf8a506e08b/include/brynet/net/TcpConnection.hpp#L1067-L1073.  left data will remain internal buffer.

**Comment by irieger** [comment]
Ok, thank you. That helped to better understand. Just returning 0 until the frame data size is met seems to work fine.

**Comment by IronsDu** [comment]
> Ok, thank you. That helped to better understand. Just returning 0 until the frame data size is met seems to work fine.

Yes，If not receive complete packet, will return 0.
